#ifndef DBUSLINK_H
#define DBUSLINK_H

#include <QObject>
#include <QLabel>
#include "dbusmoduleglobal.h"

class DbusLink : public QObject
{
    Q_OBJECT
    public:
    DbusLink(QObject *parent) : QObject{parent} {};
    public slots:
        int version(){return 1;};

        // FIELDS


        virtual QString listField(){return "";};
        virtual QString listMethod(){return "";};

        virtual bool hasField(QString name){return false;};
        virtual bool hasMethod(QString name){return false;};


        virtual int getFieldInt(QString name){return 1;};
        virtual double getFieldDouble(QString name){return 2.0;};
        virtual QString getFieldString(QString name){return "";};
        virtual QTime getFieldTime(QString name){return QTime();};
        virtual QDate getFieldDate(QString name){return QDate();};
        virtual bool getFieldBoolean(QString nam){return false;};
        virtual QString getFieldLabel(QString name){return "";};

        // METHOD



        virtual void callMethod(QString name) = 0;
        virtual void callMethod_Int(QString name,int a) = 0;
        virtual void callMethod_Int_Int(QString name,int a,int b) = 0;
        virtual void callMethod_Int_Double(QString name,int a,double b) = 0;
        virtual void callMethod_Int_Boolean(QString name,int a,bool b) = 0;
        virtual void callMethod_Int_Date(QString name,int a,QDate b) = 0;
        virtual void callMethod_Int_String(QString name,int a,QString b) = 0;
        virtual void callMethod_Int_Time(QString name,int a,QTime b) = 0;
        virtual void callMethod_Double(QString name,double a) = 0;
        virtual void callMethod_Double_Int(QString name,double a,int b) = 0;
        virtual void callMethod_Double_Double(QString name,double a,double b) = 0;
        virtual void callMethod_Double_Boolean(QString name,double a,bool b) = 0;
        virtual void callMethod_Double_Date(QString name,double a,QDate b) = 0;
        virtual void callMethod_Double_String(QString name,double a,QString b) = 0;
        virtual void callMethod_Double_Time(QString name,double a,QTime b) = 0;
        virtual void callMethod_Boolean(QString name,bool a) = 0;
        virtual void callMethod_Boolean_Int(QString name,bool a,int b) = 0;
        virtual void callMethod_Boolean_Double(QString name,bool a,double b) = 0;
        virtual void callMethod_Boolean_Boolean(QString name,bool a,bool b) = 0;
        virtual void callMethod_Boolean_Date(QString name,bool a,QDate b) = 0;
        virtual void callMethod_Boolean_String(QString name,bool a,QString b) = 0;
        virtual void callMethod_Boolean_Time(QString name,bool a,QTime b) = 0;
        virtual void callMethod_Date(QString name,QDate a) = 0;
        virtual void callMethod_Date_Int(QString name,QDate a,int b) = 0;
        virtual void callMethod_Date_Double(QString name,QDate a,double b) = 0;
        virtual void callMethod_Date_Boolean(QString name,QDate a,bool b) = 0;
        virtual void callMethod_Date_Date(QString name,QDate a,QDate b) = 0;
        virtual void callMethod_Date_String(QString name,QDate a,QString b) = 0;
        virtual void callMethod_Date_Time(QString name,QDate a,QTime b) = 0;
        virtual void callMethod_String(QString name,QString a) = 0;
        virtual void callMethod_String_Int(QString name,QString a,int b) = 0;
        virtual void callMethod_String_Double(QString name,QString a,double b) = 0;
        virtual void callMethod_String_Boolean(QString name,QString a,bool b) = 0;
        virtual void callMethod_String_Date(QString name,QString a,QDate b) = 0;
        virtual void callMethod_String_String(QString name,QString a,QString b) = 0;
        virtual void callMethod_String_Time(QString name,QString a,QTime b) = 0;
        virtual void callMethod_Time(QString name,QTime a) = 0;
        virtual void callMethod_Time_Int(QString name,QTime a,int b) = 0;
        virtual void callMethod_Time_Double(QString name,QTime a,double b) = 0;
        virtual void callMethod_Time_Boolean(QString name,QTime a,bool b) = 0;
        virtual void callMethod_Time_Date(QString name,QTime a,QDate b) = 0;
        virtual void callMethod_Time_String(QString name,QTime a,QString b) = 0;
        virtual void callMethod_Time_Time(QString name,QTime a,QTime b) = 0;
        virtual int callMethodInt(QString name) = 0;
        virtual int callMethodInt_Int_Int(QString name,int a,int b) = 0;
        virtual int callMethodInt_Int_Double(QString name,int a,double b) = 0;
        virtual int callMethodInt_Int_Boolean(QString name,int a,bool b) = 0;
        virtual int callMethodInt_Int_Date(QString name,int a,QDate b) = 0;
        virtual int callMethodInt_Int_String(QString name,int a,QString b) = 0;
        virtual int callMethodInt_Int_Time(QString name,int a,QTime b) = 0;
        virtual int callMethodInt_Int(QString name,int a) = 0;
        virtual int callMethodInt_Double_Int(QString name,double a,int b) = 0;
        virtual int callMethodInt_Double_Double(QString name,double a,double b) = 0;
        virtual int callMethodInt_Double_Boolean(QString name,double a,bool b) = 0;
        virtual int callMethodInt_Double_Date(QString name,double a,QDate b) = 0;
        virtual int callMethodInt_Double_String(QString name,double a,QString b) = 0;
        virtual int callMethodInt_Double_Time(QString name,double a,QTime b) = 0;
        virtual int callMethodInt_Double(QString name,double a) = 0;
        virtual int callMethodInt_Boolean_Int(QString name,bool a,int b) = 0;
        virtual int callMethodInt_Boolean_Double(QString name,bool a,double b) = 0;
        virtual int callMethodInt_Boolean_Boolean(QString name,bool a,bool b) = 0;
        virtual int callMethodInt_Boolean_Date(QString name,bool a,QDate b) = 0;
        virtual int callMethodInt_Boolean_String(QString name,bool a,QString b) = 0;
        virtual int callMethodInt_Boolean_Time(QString name,bool a,QTime b) = 0;
        virtual int callMethodInt_Boolean(QString name,bool a) = 0;
        virtual int callMethodInt_Date_Int(QString name,QDate a,int b) = 0;
        virtual int callMethodInt_Date_Double(QString name,QDate a,double b) = 0;
        virtual int callMethodInt_Date_Boolean(QString name,QDate a,bool b) = 0;
        virtual int callMethodInt_Date_Date(QString name,QDate a,QDate b) = 0;
        virtual int callMethodInt_Date_String(QString name,QDate a,QString b) = 0;
        virtual int callMethodInt_Date_Time(QString name,QDate a,QTime b) = 0;
        virtual int callMethodInt_Date(QString name,QDate a) = 0;
        virtual int callMethodInt_String_Int(QString name,QString a,int b) = 0;
        virtual int callMethodInt_String_Double(QString name,QString a,double b) = 0;
        virtual int callMethodInt_String_Boolean(QString name,QString a,bool b) = 0;
        virtual int callMethodInt_String_Date(QString name,QString a,QDate b) = 0;
        virtual int callMethodInt_String_String(QString name,QString a,QString b) = 0;
        virtual int callMethodInt_String_Time(QString name,QString a,QTime b) = 0;
        virtual int callMethodInt_String(QString name,QString a) = 0;
        virtual int callMethodInt_Time_Int(QString name,QTime a,int b) = 0;
        virtual int callMethodInt_Time_Double(QString name,QTime a,double b) = 0;
        virtual int callMethodInt_Time_Boolean(QString name,QTime a,bool b) = 0;
        virtual int callMethodInt_Time_Date(QString name,QTime a,QDate b) = 0;
        virtual int callMethodInt_Time_String(QString name,QTime a,QString b) = 0;
        virtual int callMethodInt_Time_Time(QString name,QTime a,QTime b) = 0;
        virtual int callMethodInt_Time(QString name,QTime a) = 0;
        virtual double callMethodDouble(QString name) = 0;
        virtual double callMethodDouble_Int_Int(QString name,int a,int b) = 0;
        virtual double callMethodDouble_Int_Double(QString name,int a,double b) = 0;
        virtual double callMethodDouble_Int_Boolean(QString name,int a,bool b) = 0;
        virtual double callMethodDouble_Int_Date(QString name,int a,QDate b) = 0;
        virtual double callMethodDouble_Int_String(QString name,int a,QString b) = 0;
        virtual double callMethodDouble_Int_Time(QString name,int a,QTime b) = 0;
        virtual double callMethodDouble_Int(QString name,int a) = 0;
        virtual double callMethodDouble_Double_Int(QString name,double a,int b) = 0;
        virtual double callMethodDouble_Double_Double(QString name,double a,double b) = 0;
        virtual double callMethodDouble_Double_Boolean(QString name,double a,bool b) = 0;
        virtual double callMethodDouble_Double_Date(QString name,double a,QDate b) = 0;
        virtual double callMethodDouble_Double_String(QString name,double a,QString b) = 0;
        virtual double callMethodDouble_Double_Time(QString name,double a,QTime b) = 0;
        virtual double callMethodDouble_Double(QString name,double a) = 0;
        virtual double callMethodDouble_Boolean_Int(QString name,bool a,int b) = 0;
        virtual double callMethodDouble_Boolean_Double(QString name,bool a,double b) = 0;
        virtual double callMethodDouble_Boolean_Boolean(QString name,bool a,bool b) = 0;
        virtual double callMethodDouble_Boolean_Date(QString name,bool a,QDate b) = 0;
        virtual double callMethodDouble_Boolean_String(QString name,bool a,QString b) = 0;
        virtual double callMethodDouble_Boolean_Time(QString name,bool a,QTime b) = 0;
        virtual double callMethodDouble_Boolean(QString name,bool a) = 0;
        virtual double callMethodDouble_Date_Int(QString name,QDate a,int b) = 0;
        virtual double callMethodDouble_Date_Double(QString name,QDate a,double b) = 0;
        virtual double callMethodDouble_Date_Boolean(QString name,QDate a,bool b) = 0;
        virtual double callMethodDouble_Date_Date(QString name,QDate a,QDate b) = 0;
        virtual double callMethodDouble_Date_String(QString name,QDate a,QString b) = 0;
        virtual double callMethodDouble_Date_Time(QString name,QDate a,QTime b) = 0;
        virtual double callMethodDouble_Date(QString name,QDate a) = 0;
        virtual double callMethodDouble_String_Int(QString name,QString a,int b) = 0;
        virtual double callMethodDouble_String_Double(QString name,QString a,double b) = 0;
        virtual double callMethodDouble_String_Boolean(QString name,QString a,bool b) = 0;
        virtual double callMethodDouble_String_Date(QString name,QString a,QDate b) = 0;
        virtual double callMethodDouble_String_String(QString name,QString a,QString b) = 0;
        virtual double callMethodDouble_String_Time(QString name,QString a,QTime b) = 0;
        virtual double callMethodDouble_String(QString name,QString a) = 0;
        virtual double callMethodDouble_Time_Int(QString name,QTime a,int b) = 0;
        virtual double callMethodDouble_Time_Double(QString name,QTime a,double b) = 0;
        virtual double callMethodDouble_Time_Boolean(QString name,QTime a,bool b) = 0;
        virtual double callMethodDouble_Time_Date(QString name,QTime a,QDate b) = 0;
        virtual double callMethodDouble_Time_String(QString name,QTime a,QString b) = 0;
        virtual double callMethodDouble_Time_Time(QString name,QTime a,QTime b) = 0;
        virtual double callMethodDouble_Time(QString name,QTime a) = 0;
        virtual bool callMethodBoolean(QString name) = 0;
        virtual bool callMethodBoolean_Int_Int(QString name,int a,int b) = 0;
        virtual bool callMethodBoolean_Int_Double(QString name,int a,double b) = 0;
        virtual bool callMethodBoolean_Int_Boolean(QString name,int a,bool b) = 0;
        virtual bool callMethodBoolean_Int_Date(QString name,int a,QDate b) = 0;
        virtual bool callMethodBoolean_Int_String(QString name,int a,QString b) = 0;
        virtual bool callMethodBoolean_Int_Time(QString name,int a,QTime b) = 0;
        virtual bool callMethodBoolean_Int(QString name,int a) = 0;
        virtual bool callMethodBoolean_Double_Int(QString name,double a,int b) = 0;
        virtual bool callMethodBoolean_Double_Double(QString name,double a,double b) = 0;
        virtual bool callMethodBoolean_Double_Boolean(QString name,double a,bool b) = 0;
        virtual bool callMethodBoolean_Double_Date(QString name,double a,QDate b) = 0;
        virtual bool callMethodBoolean_Double_String(QString name,double a,QString b) = 0;
        virtual bool callMethodBoolean_Double_Time(QString name,double a,QTime b) = 0;
        virtual bool callMethodBoolean_Double(QString name,double a) = 0;
        virtual bool callMethodBoolean_Boolean_Int(QString name,bool a,int b) = 0;
        virtual bool callMethodBoolean_Boolean_Double(QString name,bool a,double b) = 0;
        virtual bool callMethodBoolean_Boolean_Boolean(QString name,bool a,bool b) = 0;
        virtual bool callMethodBoolean_Boolean_Date(QString name,bool a,QDate b) = 0;
        virtual bool callMethodBoolean_Boolean_String(QString name,bool a,QString b) = 0;
        virtual bool callMethodBoolean_Boolean_Time(QString name,bool a,QTime b) = 0;
        virtual bool callMethodBoolean_Boolean(QString name,bool a) = 0;
        virtual bool callMethodBoolean_Date_Int(QString name,QDate a,int b) = 0;
        virtual bool callMethodBoolean_Date_Double(QString name,QDate a,double b) = 0;
        virtual bool callMethodBoolean_Date_Boolean(QString name,QDate a,bool b) = 0;
        virtual bool callMethodBoolean_Date_Date(QString name,QDate a,QDate b) = 0;
        virtual bool callMethodBoolean_Date_String(QString name,QDate a,QString b) = 0;
        virtual bool callMethodBoolean_Date_Time(QString name,QDate a,QTime b) = 0;
        virtual bool callMethodBoolean_Date(QString name,QDate a) = 0;
        virtual bool callMethodBoolean_String_Int(QString name,QString a,int b) = 0;
        virtual bool callMethodBoolean_String_Double(QString name,QString a,double b) = 0;
        virtual bool callMethodBoolean_String_Boolean(QString name,QString a,bool b) = 0;
        virtual bool callMethodBoolean_String_Date(QString name,QString a,QDate b) = 0;
        virtual bool callMethodBoolean_String_String(QString name,QString a,QString b) = 0;
        virtual bool callMethodBoolean_String_Time(QString name,QString a,QTime b) = 0;
        virtual bool callMethodBoolean_String(QString name,QString a) = 0;
        virtual bool callMethodBoolean_Time_Int(QString name,QTime a,int b) = 0;
        virtual bool callMethodBoolean_Time_Double(QString name,QTime a,double b) = 0;
        virtual bool callMethodBoolean_Time_Boolean(QString name,QTime a,bool b) = 0;
        virtual bool callMethodBoolean_Time_Date(QString name,QTime a,QDate b) = 0;
        virtual bool callMethodBoolean_Time_String(QString name,QTime a,QString b) = 0;
        virtual bool callMethodBoolean_Time_Time(QString name,QTime a,QTime b) = 0;
        virtual bool callMethodBoolean_Time(QString name,QTime a) = 0;
        virtual QDate callMethodDate(QString name) = 0;
        virtual QDate callMethodDate_Int_Int(QString name,int a,int b) = 0;
        virtual QDate callMethodDate_Int_Double(QString name,int a,double b) = 0;
        virtual QDate callMethodDate_Int_Boolean(QString name,int a,bool b) = 0;
        virtual QDate callMethodDate_Int_Date(QString name,int a,QDate b) = 0;
        virtual QDate callMethodDate_Int_String(QString name,int a,QString b) = 0;
        virtual QDate callMethodDate_Int_Time(QString name,int a,QTime b) = 0;
        virtual QDate callMethodDate_Int(QString name,int a) = 0;
        virtual QDate callMethodDate_Double_Int(QString name,double a,int b) = 0;
        virtual QDate callMethodDate_Double_Double(QString name,double a,double b) = 0;
        virtual QDate callMethodDate_Double_Boolean(QString name,double a,bool b) = 0;
        virtual QDate callMethodDate_Double_Date(QString name,double a,QDate b) = 0;
        virtual QDate callMethodDate_Double_String(QString name,double a,QString b) = 0;
        virtual QDate callMethodDate_Double_Time(QString name,double a,QTime b) = 0;
        virtual QDate callMethodDate_Double(QString name,double a) = 0;
        virtual QDate callMethodDate_Boolean_Int(QString name,bool a,int b) = 0;
        virtual QDate callMethodDate_Boolean_Double(QString name,bool a,double b) = 0;
        virtual QDate callMethodDate_Boolean_Boolean(QString name,bool a,bool b) = 0;
        virtual QDate callMethodDate_Boolean_Date(QString name,bool a,QDate b) = 0;
        virtual QDate callMethodDate_Boolean_String(QString name,bool a,QString b) = 0;
        virtual QDate callMethodDate_Boolean_Time(QString name,bool a,QTime b) = 0;
        virtual QDate callMethodDate_Boolean(QString name,bool a) = 0;
        virtual QDate callMethodDate_Date_Int(QString name,QDate a,int b) = 0;
        virtual QDate callMethodDate_Date_Double(QString name,QDate a,double b) = 0;
        virtual QDate callMethodDate_Date_Boolean(QString name,QDate a,bool b) = 0;
        virtual QDate callMethodDate_Date_Date(QString name,QDate a,QDate b) = 0;
        virtual QDate callMethodDate_Date_String(QString name,QDate a,QString b) = 0;
        virtual QDate callMethodDate_Date_Time(QString name,QDate a,QTime b) = 0;
        virtual QDate callMethodDate_Date(QString name,QDate a) = 0;
        virtual QDate callMethodDate_String_Int(QString name,QString a,int b) = 0;
        virtual QDate callMethodDate_String_Double(QString name,QString a,double b) = 0;
        virtual QDate callMethodDate_String_Boolean(QString name,QString a,bool b) = 0;
        virtual QDate callMethodDate_String_Date(QString name,QString a,QDate b) = 0;
        virtual QDate callMethodDate_String_String(QString name,QString a,QString b) = 0;
        virtual QDate callMethodDate_String_Time(QString name,QString a,QTime b) = 0;
        virtual QDate callMethodDate_String(QString name,QString a) = 0;
        virtual QDate callMethodDate_Time_Int(QString name,QTime a,int b) = 0;
        virtual QDate callMethodDate_Time_Double(QString name,QTime a,double b) = 0;
        virtual QDate callMethodDate_Time_Boolean(QString name,QTime a,bool b) = 0;
        virtual QDate callMethodDate_Time_Date(QString name,QTime a,QDate b) = 0;
        virtual QDate callMethodDate_Time_String(QString name,QTime a,QString b) = 0;
        virtual QDate callMethodDate_Time_Time(QString name,QTime a,QTime b) = 0;
        virtual QDate callMethodDate_Time(QString name,QTime a) = 0;
        virtual QString callMethodString(QString name) = 0;
        virtual QString callMethodString_Int_Int(QString name,int a,int b) = 0;
        virtual QString callMethodString_Int_Double(QString name,int a,double b) = 0;
        virtual QString callMethodString_Int_Boolean(QString name,int a,bool b) = 0;
        virtual QString callMethodString_Int_Date(QString name,int a,QDate b) = 0;
        virtual QString callMethodString_Int_String(QString name,int a,QString b) = 0;
        virtual QString callMethodString_Int_Time(QString name,int a,QTime b) = 0;
        virtual QString callMethodString_Int(QString name,int a) = 0;
        virtual QString callMethodString_Double_Int(QString name,double a,int b) = 0;
        virtual QString callMethodString_Double_Double(QString name,double a,double b) = 0;
        virtual QString callMethodString_Double_Boolean(QString name,double a,bool b) = 0;
        virtual QString callMethodString_Double_Date(QString name,double a,QDate b) = 0;
        virtual QString callMethodString_Double_String(QString name,double a,QString b) = 0;
        virtual QString callMethodString_Double_Time(QString name,double a,QTime b) = 0;
        virtual QString callMethodString_Double(QString name,double a) = 0;
        virtual QString callMethodString_Boolean_Int(QString name,bool a,int b) = 0;
        virtual QString callMethodString_Boolean_Double(QString name,bool a,double b) = 0;
        virtual QString callMethodString_Boolean_Boolean(QString name,bool a,bool b) = 0;
        virtual QString callMethodString_Boolean_Date(QString name,bool a,QDate b) = 0;
        virtual QString callMethodString_Boolean_String(QString name,bool a,QString b) = 0;
        virtual QString callMethodString_Boolean_Time(QString name,bool a,QTime b) = 0;
        virtual QString callMethodString_Boolean(QString name,bool a) = 0;
        virtual QString callMethodString_Date_Int(QString name,QDate a,int b) = 0;
        virtual QString callMethodString_Date_Double(QString name,QDate a,double b) = 0;
        virtual QString callMethodString_Date_Boolean(QString name,QDate a,bool b) = 0;
        virtual QString callMethodString_Date_Date(QString name,QDate a,QDate b) = 0;
        virtual QString callMethodString_Date_String(QString name,QDate a,QString b) = 0;
        virtual QString callMethodString_Date_Time(QString name,QDate a,QTime b) = 0;
        virtual QString callMethodString_Date(QString name,QDate a) = 0;
        virtual QString callMethodString_String_Int(QString name,QString a,int b) = 0;
        virtual QString callMethodString_String_Double(QString name,QString a,double b) = 0;
        virtual QString callMethodString_String_Boolean(QString name,QString a,bool b) = 0;
        virtual QString callMethodString_String_Date(QString name,QString a,QDate b) = 0;
        virtual QString callMethodString_String_String(QString name,QString a,QString b) = 0;
        virtual QString callMethodString_String_Time(QString name,QString a,QTime b) = 0;
        virtual QString callMethodString_String(QString name,QString a) = 0;
        virtual QString callMethodString_Time_Int(QString name,QTime a,int b) = 0;
        virtual QString callMethodString_Time_Double(QString name,QTime a,double b) = 0;
        virtual QString callMethodString_Time_Boolean(QString name,QTime a,bool b) = 0;
        virtual QString callMethodString_Time_Date(QString name,QTime a,QDate b) = 0;
        virtual QString callMethodString_Time_String(QString name,QTime a,QString b) = 0;
        virtual QString callMethodString_Time_Time(QString name,QTime a,QTime b) = 0;
        virtual QString callMethodString_Time(QString name,QTime a) = 0;
        virtual QTime callMethodTime(QString name) = 0;
        virtual QTime callMethodTime_Int_Int(QString name,int a,int b) = 0;
        virtual QTime callMethodTime_Int_Double(QString name,int a,double b) = 0;
        virtual QTime callMethodTime_Int_Boolean(QString name,int a,bool b) = 0;
        virtual QTime callMethodTime_Int_Date(QString name,int a,QDate b) = 0;
        virtual QTime callMethodTime_Int_String(QString name,int a,QString b) = 0;
        virtual QTime callMethodTime_Int_Time(QString name,int a,QTime b) = 0;
        virtual QTime callMethodTime_Int(QString name,int a) = 0;
        virtual QTime callMethodTime_Double_Int(QString name,double a,int b) = 0;
        virtual QTime callMethodTime_Double_Double(QString name,double a,double b) = 0;
        virtual QTime callMethodTime_Double_Boolean(QString name,double a,bool b) = 0;
        virtual QTime callMethodTime_Double_Date(QString name,double a,QDate b) = 0;
        virtual QTime callMethodTime_Double_String(QString name,double a,QString b) = 0;
        virtual QTime callMethodTime_Double_Time(QString name,double a,QTime b) = 0;
        virtual QTime callMethodTime_Double(QString name,double a) = 0;
        virtual QTime callMethodTime_Boolean_Int(QString name,bool a,int b) = 0;
        virtual QTime callMethodTime_Boolean_Double(QString name,bool a,double b) = 0;
        virtual QTime callMethodTime_Boolean_Boolean(QString name,bool a,bool b) = 0;
        virtual QTime callMethodTime_Boolean_Date(QString name,bool a,QDate b) = 0;
        virtual QTime callMethodTime_Boolean_String(QString name,bool a,QString b) = 0;
        virtual QTime callMethodTime_Boolean_Time(QString name,bool a,QTime b) = 0;
        virtual QTime callMethodTime_Boolean(QString name,bool a) = 0;
        virtual QTime callMethodTime_Date_Int(QString name,QDate a,int b) = 0;
        virtual QTime callMethodTime_Date_Double(QString name,QDate a,double b) = 0;
        virtual QTime callMethodTime_Date_Boolean(QString name,QDate a,bool b) = 0;
        virtual QTime callMethodTime_Date_Date(QString name,QDate a,QDate b) = 0;
        virtual QTime callMethodTime_Date_String(QString name,QDate a,QString b) = 0;
        virtual QTime callMethodTime_Date_Time(QString name,QDate a,QTime b) = 0;
        virtual QTime callMethodTime_Date(QString name,QDate a) = 0;
        virtual QTime callMethodTime_String_Int(QString name,QString a,int b) = 0;
        virtual QTime callMethodTime_String_Double(QString name,QString a,double b) = 0;
        virtual QTime callMethodTime_String_Boolean(QString name,QString a,bool b) = 0;
        virtual QTime callMethodTime_String_Date(QString name,QString a,QDate b) = 0;
        virtual QTime callMethodTime_String_String(QString name,QString a,QString b) = 0;
        virtual QTime callMethodTime_String_Time(QString name,QString a,QTime b) = 0;
        virtual QTime callMethodTime_String(QString name,QString a) = 0;
        virtual QTime callMethodTime_Time_Int(QString name,QTime a,int b) = 0;
        virtual QTime callMethodTime_Time_Double(QString name,QTime a,double b) = 0;
        virtual QTime callMethodTime_Time_Boolean(QString name,QTime a,bool b) = 0;
        virtual QTime callMethodTime_Time_Date(QString name,QTime a,QDate b) = 0;
        virtual QTime callMethodTime_Time_String(QString name,QTime a,QString b) = 0;
        virtual QTime callMethodTime_Time_Time(QString name,QTime a,QTime b) = 0;
        virtual QTime callMethodTime_Time(QString name,QTime a) = 0;

    private:
        DbusModuleGlobal *core;
};


#endif // DBUSLINK_H
